version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: pesho
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db
